freebsd_instance:
  image_family: freebsd-12-1

freebsd_task:
  env:
    OPAMYES: 1
  env:
    matrix:
      - OCAML_VERSION: 4.13.1
      - OCAML_VERSION: 4.14.0
  pkg_install_script: pkg install -y ocaml-opam binutils gmake bash
  opam_ocaml_cache:
    folder: $HOME/.opam
    reupload_on_changes: false
    fingerprint_script:
      - echo $CIRRUS_OS
      - echo $OCAML_VERSION
    populate_script:
      - opam init -a --comp=$OCAML_VERSION
  setup_script:
    - opam update
    - opam install dune
    - opam pin add -n -t .
    - opam depext -yt cosmopolitan esperanto
    - opam install -v -t cosmopolitan esperanto --deps-only
  build_script: opam reinstall -t -v cosmopolitan esperanto
  test_script:
    - cd example/
    - opam install ocamlfind
    - opam exec -- dune build ./cat.com
    - bash -c './cat.com < cat.ml'
